# Generated by Django 2.1.9 on 2020-06-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aloeapp', '0002_auto_20200408_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activa', models.BooleanField(blank=True, default=False, help_text='Ten activo solo uno al mismo tiempo')),
            ],
        ),
    ]
