# Generated by Django 2.1.9 on 2020-04-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aloe_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField(default=10)),
                ('discount', models.IntegerField(default=0)),
                ('new', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=3.5)),
                ('saleCount', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=200, null=True)),
                ('tag', models.CharField(max_length=200, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('image', models.ImageField(max_length=255, null=True, upload_to='myphoto/%Y/%m/%d/')),
                ('shortDescription', models.CharField(max_length=500, null=True)),
                ('fullDescription', models.CharField(max_length=1500, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Ejemplo',
        ),
    ]
